### ISSUE TITLE
Question about changing EnableSendfile to On?

### ISSUE THREAD

**Issue by ghost** [publicisworldwide/docker-stacks#31]
After pulling the image we notice that `EnableSendfile` is set to `on` in `/etc/httpd/conf/httpd.conf`, whose default is `Off`. 

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#enablesendfile) recommends to set `EnableSendfile` to `Off` to avoid operational problems when:
* Some platforms may have broken sendfile support that the build system did not detect, especially if the binaries were built on another box and moved to such a machine with broken sendfile support.
* On Linux the use of sendfile triggers TCP-checksum offloading bugs on certain networking cards when using IPv6.
* On Linux on Itanium, sendfile may be unable to handle files over 2GB in size.
* With a network-mounted DocumentRoot (e.g., NFS, SMB, CIFS, FUSE), the kernel may be unable to serve the network file through its own cache.

Maybe it's better to set `EnableSendfile` should be changed back to `off` as default.

**Comment by Reamer** [comment]
Hi @HCHCHH 
We are aware of these limitations. We disable Sendfile for directories, which are network-mounted. This docker image is only used on new linux kernels, which should support this feature. Intel Itanium and buggy network cards are not in use.

**Comment by ghost** [comment]
Thank you for your response! Your configuration makes sense for your use case.
